swagger: '2.0'
info:
  title: phrasing API
  description:  Weather and air quality information as phrases and structural data.
  version: "0.0.1"
# during dev, should point to your local machine
#host: localhost:10010
host: phrasing-weather.herokuapp.com
schemes:
  # tip: remove http to make production-grade
  - https
  - http
basePath: /v1
produces:
  - application/json
paths:
  /stations:
    # vastaa api/controllers hakemistossa olevaa moduulia
    x-swagger-router-controller: stations
    get:
      # vastaa metodin nimeä kontrolelrissa
      operationId: getStations
      summary: List cities that have  weather and/or airquality information.
      responses:
        200:
          description: List of cities.
          schema:
            $ref: '#/definitions/Stations'
    
  /stations/{city}:
    # binds a127 app logic to a route
    # vastaa api/controllers hakemistossa olevaa moduulia
    x-swagger-router-controller: api
    get:
      summary: Weather and air quality info
      # vastaa api moduulin funktiota
      operationId: getData
      description: |
        The weather endpoint returns information about the weather and air quality.
        The response includes the details at a given location.
      parameters:
        - name: city
          in: path
          description: City of the weather info.
          required: true
          type: string
      tags:
        - Details
      responses:
        200:
          description: An object containing weather and airquality info for the city
          schema:
            $ref: '#/definitions/Weather'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Stations:
    type: object
    additionalProperties:
       type: object
       properties:
          hasAirquality:
             type: boolean
             description: does the city have airquality information available
          hasWeather:
             type: boolean
             description: does the city have weather  information available

  Weather:
    type: object
    properties:
      hasWeather:
        type: boolean
        description: Does the response contain weather information.
      hasAirquality:
         type: boolean
         description: Does the response contain airquality information.
      city:
        type: string
        description: City of the weather query.
      temperature:
        type: number
        description: Temperature in celsius.
      windDirection:
        type: string
        description: Direction of the wind in N|NE|E|SE|S|SW|W|NW
      windSpeed:
        type: integer
        description: Speed of the wind in meters per second.
      clouds:
        type: string
        description: Cloud coverage described.
      airquality:
         type: array
         items:
           type: object
           properties:
              station:
                 type: string
                 description: name of the airquality measuring station
              index:
                 type: integer
                 description: Air quality represented as an integer from 1 (good) to 5
              FI:
                 type: string
                 description: Finnish  word describing the airquality.
              EN:
                 type: string
                 description: English  word describing the airquality.
              error:
                 type: boolean
                 description: Is there a measurement available from this station.
              time:
                 type: integer
                 description: The hour of the measurement as an integer from 0 to 23
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      fields:
        type: string
