swagger: '2.0'
info:
  title: phrasing API
  description:  Weather and air quality information as phrases and structural data.
  version: "0.0.1"
# during dev, should point to your local machine
host: localhost:10010
#host: phrasing-weather.herokuapp.com
schemes:
  # tip: remove http to make production-grade
  - https
  - http
basePath: /v1
produces:
  - application/json
paths:
  # /swagger palauttaa tämän swagger kuvauksen JSON muodossa
  /swagger:
    x-swagger-pipe: swagger_raw
  /weather:
    # binds a127 app logic to a route
    # vastaa api/controllers hakemistossa olevaa moduulia
    x-swagger-router-controller: api
    get:
      summary: Weather and air quality info
      # vastaa api moduulin funktiota
      operationId: getData
      description: |
        The weather endpoint returns information about the weather and air quality.
        The response includes the details at a given location.
      parameters:
        - name: city
          in: query
          description: City of the weather info.
          required: true
          type: string
      tags:
        - Details
      responses:
        200:
          description: An array of weather info for the city
          schema:
            $ref: '#/definitions/Weather'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Weather:
    type: object
    properties:
      city:
        type: string
        description: City of the weather query.
      temperature:
        type: string
        description: Temperature in celsius.
      windDirection:
        type: string
        description: Direction of the wind in N|NE|E|SE|S|SW|W|NW
      windSpeed:
        type: string
        description: Speed of the wind in meters per second.
      clouds:
        type: string
        description: Cloud coverage described.
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      fields:
        type: string
